name: Build and Release (CNVC Branch)

on:
  workflow_dispatch:
    inputs:
      rebuild:
        description: '忽略构建记录以重新构建'
        required: false
        type: boolean
      donotpublish:
        description: '构建后不提交发布新版'
        required: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java_ver: [17]
    steps:
      - name: Checkout cnvc branch
        uses: actions/checkout@v4
        with:
          ref: cnvc  # 指定检出 cnvc 分支
          fetch-depth: 0

      - name: Set Build Time (Beijing Time)
        run: |
          beijing_time=$(date -d "+8 hours" +'%Y%m%d-%H%M')
          echo "tag=$beijing_time" >> $GITHUB_ENV  # 添加 CNVC 前缀

      - name: Modify Version and About Dialog
        run: |
          echo '修改 VersionName 和 About Dialog'
          # 修改为 CNVC 前缀
          sed -i "/versionName/s#[0-9a-zA-Z_\.\'\"-]\+\$#\'HGTV-${{ env.tag }}\'#" ${{ github.workspace }}/app/build.gradle
          sed -i "/android:text=\"/s#HGTV-[0-9]\{8\}-[0-9]\{4\}#HGTV-${{ env.tag }}#g" ${{ github.workspace }}/app/src/main/res/layout/dialog_about.xml

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java_ver }}

      - uses: gradle/actions/setup-gradle@v4

      - name: Build With Gradle
        run: |
          chmod +x gradlew
          ./gradlew assemblerelease --build-cache --parallel --daemon --warning-mode all

      - name: Prepare App
        run: |
          rm -rf apk/
          mkdir -p apk/
          for file in `find ~ -name "*release*.apk" -print`; do
            mv "$file" apk/HGTV_${{ env.tag }}.apk  # 修改产物名称
          done

      - name: Generate Release Notes
        run: |
          export LESSCHARSET=utf-8
          echo -e "Build Time: ${{ env.tag }}\nBranch: cnvc\nCommit: $(git rev-parse --short HEAD)\nChangelog:\n\`\`\`" > apk/Release.log
          git log --pretty=format:%B -n 5 | sed -e "s# \{2,\}#\n#g" -e "/^Merge \(pull\|branch\|remote\)/d" -e '/^$/d' | cat -n | sort -k2,2 -k1,1n | uniq -f1 | sort -k1,1n | cut -f2- >> apk/Release.log
          echo -e '\n```' >> apk/Release.log

      - name: Upload App To Artifact
        uses: actions/upload-artifact@v4
        with:
          name: CNVC-Release  # 修改产物名称
          path: |
            ${{ github.workspace }}/apk/*

      - name: Release and Upload Assets
        uses: ncipollo/release-action@v1
        with:
          name: ${{ env.tag }}
          tag: ${{ env.tag }}
          bodyFile: ${{ github.workspace }}/apk/Release.log
          allowUpdates: true
          removeArtifacts: true
          artifacts: |
            ${{ github.workspace }}/apk/*.apk

      - name: Post To Telegram
        if: ${{ github.event_name == 'workflow_dispatch' }}
        env:
          CHAT_ID: -1001734684817
          TELEGRAM_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          if [ -n "$TELEGRAM_TOKEN" ]; then
            sed -i -e '1s/\[\(.*\)\].*/#\1/' -e 's#\([&"\/]\)#\\\1#g' apk/Release.log
            mv -f apk/Release.log caption.txt
            chmod +x telegram-bot-api-binary
            ./telegram-bot-api-binary --api-id=21724 --api-hash=3e0cb5efcd52300aec5994fdfc5bdc16 --local 2>&1 > /dev/null &
            mv ../.github/scripts/upload.py ./
            python upload.py
          else
            echo "TELEGRAM_TOKEN is not set, skipping Telegram notification."
          fi

      - name: Push to CNVC Branch
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote set-url --add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          
          # 切换到 cnvc 分支
          git checkout cnvc
          
          # 提交所有更改
          git add --all
          git commit -m "Auto-commit changes before rebase (CNVC)"

          # 拉取最新代码并 rebase
          git pull --rebase origin cnvc

          # 更新 README.md
          sed -i "/Updated:/s#Updated: [a-zA-Z0-9-]*#Updated: HGTV-${{ env.tag }}#" README.md
          git add README.md
          git commit -m "HGTV-${{ env.tag }}"

          # 强制推送到 cnvc 分支
          git push -u -f origin cnvc  # 修改推送目标分支
